import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication

logger = logging.getLogger(__name__)

# --- CONFIGURE THESE ---
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = "certichainnoreply@gmail.com"
SMTP_PASS = "jhuk ynmu eumz tfgh"
ADMIN_EMAIL = "vermashivika072@gmail.com"
# -----------------------


def send_report_email(
    user_email: str,
    certificate_name: str,
    certificate_id: str,
    status: str,
    score: float,
    ai_summary: str,
    pdf_bytes: bytes | None = None,
) -> bool:
    """
    Sends the forensic analysis report to the user and admin via email.
    Attaches the PDF report if provided.
    Returns True on success, False on failure (silent, no crash).
    """
    try:
        is_genuine = status.lower() == "real"
        verdict = "✅ GENUINE" if is_genuine else "❌ FAKE / TAMPERED"
        score_pct = int(score * 100)

        subject = f"CertiChain Aura — Forensic Report: {certificate_name} [{verdict}]"
        
        # If user email is a system/demo email, send to admin directly
        SYSTEM_DOMAINS = ["certichain.ai", "certichain.io", "certichain.com"]
        is_system_email = not user_email or any(user_email.endswith(d) for d in SYSTEM_DOMAINS)
        effective_to = ADMIN_EMAIL if is_system_email else user_email


        html_body = f"""
        <html><body style="font-family: Arial, sans-serif; background:#0f172a; color:#e2e8f0; padding:30px;">
          <div style="max-width:600px; margin:auto; background:#1e293b; border-radius:16px; overflow:hidden;">
            <div style="background: linear-gradient(135deg, #0ea5e9, #6366f1); padding:24px; text-align:center;">
              <h1 style="color:white; margin:0; font-size:24px;">🔐 CertiChain Aura</h1>
              <p style="color:#e0f2fe; margin:4px 0 0;">Official Forensic Audit Report</p>
            </div>
            <div style="padding:28px;">
              <h2 style="color:{'#4ade80' if is_genuine else '#f87171'}; font-size:20px; margin-top:0;">
                Verdict: {verdict}
              </h2>
              <table style="width:100%; border-collapse:collapse; margin-bottom:20px;">
                <tr style="border-bottom:1px solid #334155;">
                  <td style="padding:10px; color:#94a3b8; font-size:13px;">Certificate ID</td>
                  <td style="padding:10px; font-size:13px; word-break:break-all;">{certificate_id}</td>
                </tr>
                <tr style="border-bottom:1px solid #334155;">
                  <td style="padding:10px; color:#94a3b8; font-size:13px;">Candidate Name</td>
                  <td style="padding:10px; font-size:13px;">{certificate_name}</td>
                </tr>
                <tr>
                  <td style="padding:10px; color:#94a3b8; font-size:13px;">Authenticity Score</td>
                  <td style="padding:10px; font-size:13px; color:{'#4ade80' if is_genuine else '#f87171'}; font-weight:bold;">{score_pct}%</td>
                </tr>
              </table>

              <div style="background:#0f172a; border-left:4px solid #0ea5e9; border-radius:8px; padding:16px; margin-bottom:20px;">
                <h3 style="color:#38bdf8; margin:0 0 8px;">🤖 AI Deep Learning Analysis</h3>
                <p style="font-size:13px; line-height:1.7; margin:0; color:#cbd5e1;">{ai_summary}</p>
              </div>

              <p style="font-size:12px; color:#64748b; margin-top:24px;">
                This report was automatically generated by CertiChain Aura's AI forensic engine.
                Please find the full PDF report attached.
              </p>
            </div>
          </div>
        </body></html>
        """

        # Build the email
        msg = MIMEMultipart("mixed")
        msg["Subject"] = subject
        msg["From"] = f"CertiChain Aura <{SMTP_USER}>"
        msg["To"] = effective_to
        msg["Cc"] = ADMIN_EMAIL if not is_system_email else ""

        msg.attach(MIMEText(html_body, "html"))

        # Attach PDF if available
        if pdf_bytes:
            attachment = MIMEApplication(pdf_bytes, _subtype="pdf")
            attachment.add_header(
                "Content-Disposition",
                "attachment",
                filename=f"certichain_report_{certificate_id[:8]}.pdf",
            )
            msg.attach(attachment)

        # Build recipients list (avoid duplicates)
        recipients = list({effective_to, ADMIN_EMAIL})

        # Send via Gmail SMTP
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.sendmail(SMTP_USER, recipients, msg.as_string())

        logger.info(f"[EMAIL] Report sent to {user_email} and {ADMIN_EMAIL} for cert {certificate_id}")
        return True

    except Exception as e:
        logger.error(f"[EMAIL ERROR] Could not send report email: {e}")
        print(f"[EMAIL ERROR] {e}")
        return False
